AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB table for Task Management App"

Resources:
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-tasks
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref AWS::StackName

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref TasksTable
    Export:
      Name: !Sub ${AWS::StackName}-TableName
